name: Despliegue Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar kubectl
        run: |
          kubectl config set-credentials kube-user --token=${{ secrets.KUBE_TOKEN }} --server=${{ secrets.KUBE_API_URL }}
          kubectl config set-context kube-context --cluster=kube-cluster --user=kube-user
          kubectl config use-context kube-context

      - name: Desplegar la aplicación
        run: kubectl apply -f manifestos/mi-app.yaml
